apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.monitoring.loki.service.name }}
spec:
  selector:
    app: loki
  ports:
    - port: {{ .Values.monitoring.loki.service.port }}
      targetPort: {{ .Values.monitoring.loki.service.port }}
  type: {{ .Values.monitoring.loki.service.type }}