apiVersion: v1
kind: ConfigMap
metadata:
  name: regression-worker-config
  labels:
    app: regression-worker
data:
  REDIS_URL: "redis://redis-svc:6379"
  PUSHGATEWAY_URL: "http://pushgateway-svc:9091"
