apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: "api"
        static_configs:
          - targets: ["{{ .Values.serviceNames.api }}:{{ .Values.api.service.port }}"]

      - job_name: "pushgateway"
        static_configs:
          - targets: ["{{ .Values.serviceNames.pushgateway }}:{{ .Values.monitoring.pushgateway.service.port }}"]