apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.monitoring.prometheus.service.name }}
spec:
  selector:
    app: prometheus
  ports:
    - port: {{ .Values.monitoring.prometheus.service.port }}
      targetPort: {{ .Values.monitoring.prometheus.service.port }}
  type: {{ .Values.monitoring.prometheus.service.type }}