apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.monitoring.grafana.service.name }}
spec:
  selector:
    app: grafana
  ports:
    - port: {{ .Values.monitoring.grafana.service.port }}
      targetPort: {{ .Values.monitoring.grafana.service.port }}
  type: {{ .Values.monitoring.grafana.service.type }}